# Generated by Django 4.2.7 on 2023-11-18 22:16

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_blogcategory_blogindexpage_blogpostpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpostpage",
            name="intro",
            field=wagtail.fields.RichTextField(blank=True),
        ),
    ]
