# Generated by Django 4.2.7 on 2023-11-27 22:00

from django.db import migrations
import home.models
import wagtail.blocks
import wagtail.documents.blocks
import wagtail.fields
import wagtail.images.blocks
import wagtail.snippets.blocks


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_blogpostpage_intro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpostpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("heading", wagtail.blocks.CharBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "stream",
                        wagtail.blocks.StreamBlock(
                            [("paragraph", wagtail.blocks.CharBlock())]
                        ),
                    ),
                    (
                        "stream_nested",
                        wagtail.blocks.StreamBlock(
                            [
                                (
                                    "stream",
                                    wagtail.blocks.StreamBlock(
                                        [("paragraph", wagtail.blocks.CharBlock())]
                                    ),
                                )
                            ]
                        ),
                    ),
                    ("list", wagtail.blocks.ListBlock(wagtail.blocks.CharBlock())),
                    (
                        "list_nested",
                        wagtail.blocks.ListBlock(
                            wagtail.blocks.ListBlock(wagtail.blocks.CharBlock())
                        ),
                    ),
                    (
                        "struct",
                        wagtail.blocks.StructBlock(
                            [
                                ("paragraph", wagtail.blocks.CharBlock()),
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                            ]
                        ),
                    ),
                    (
                        "image_struct",
                        wagtail.blocks.StructBlock(
                            [
                                ("image", wagtail.images.blocks.ImageChooserBlock()),
                                ("caption", wagtail.blocks.CharBlock(required=False)),
                            ]
                        ),
                    ),
                    ("raw", wagtail.blocks.RawHTMLBlock()),
                    ("blockquoteblock", wagtail.blocks.BlockQuoteBlock()),
                    ("page", wagtail.blocks.PageChooserBlock()),
                    ("document", wagtail.documents.blocks.DocumentChooserBlock()),
                    ("image_chooser", wagtail.images.blocks.ImageChooserBlock()),
                    (
                        "snippet",
                        wagtail.snippets.blocks.SnippetChooserBlock(
                            home.models.BlogCategory
                        ),
                    ),
                ],
                use_json_field=True,
            ),
        ),
    ]
